### ISSUE TITLE
[Suggestion]移除input

### ISSUE THREAD

**Issue by AkkoYK** [XzaiCloud/AI-Vtuber-Kun#5]
建议在README中引导用户自行打开main.py进行编辑，理由如下:

- 若经常使用，每次启动时都需输入很不便。
- 在命令行中很容易键入错误。
- 编辑config有手就行，易于检查及排错。如果有用户做不到的话增加门槛也不是坏事，避免无效交流。

**Comment by XzaiCloud** [comment]
#2

**Comment by Jrojro728** [comment]
@AkkoYK 其实我当时的意思是写个配置文件但是没有表达清楚,抱歉

**Comment by XzaiCloud** [comment]
好的，有时间我会改进的
